add lnmp.org.v1.5beta

diff --git a/conf/lamp b/conf/lamp
--- a/conf/lamp
+++ b/conf/lamp
@@ -34,7 +34,7 @@ lamp_stop()
 lamp_reload()
 {
     echo "Reload LAMP..."
-    /etc/init.d/httpd reload
+    /etc/init.d/httpd graceful
     /etc/init.d/mysql reload
 }
 
@@ -204,6 +204,7 @@ Add_VHost()
     read access_log
     if [[ "${access_log}" == "n" || "${access_log}" == "" ]]; then
         echo "Disable access log."
+        al_name="${domain}"
     else
         Echo_Yellow "Enter access log filename(Default:${domain}-access_log): "
         read al_name
@@ -214,16 +215,14 @@ Add_VHost()
     fi
 
     email=""
-    while :;do
-        Echo_Yellow "Please enter Administrator Email Address: "
-        read email
-        if [ "${email}" == "" ]; then
-            Echo_Red "Administrator Email Address cannot be empty!"
-        else
-            echo "Server Administrator Email:${email}"
-            break
-        fi
-    done
+    Echo_Yellow "Please enter Administrator Email Address: "
+    read email
+    if [ "${email}" == "" ]; then
+        echo "Administrator Email Address will set to webmaster@example.com!"
+        email='webmaster@example.com'
+    else
+        echo "Server Administrator Email:${email}"
+    fi
 
     if [[ -s /usr/local/mysql/bin/mysql || -s /usr/local/mariadb/bin/mysql ]]; then
         Echo_Yellow "Create database and MySQL user with same name (y/n) "
@@ -426,7 +425,20 @@ Add_Database_Menu()
 
 Add_Database()
 {
-    cat >/tmp/.add_mysql.sql<<EOF
+    if echo "${MySQL_Ver}" | grep -Eqi '^8.0.';then
+        cat >/tmp/.add_mysql.sql<<EOF
+CREATE USER '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
+CREATE USER '${database_name}'@'127.0.0.1' IDENTIFIED BY '${mysql_password}';
+GRANT USAGE ON *.* TO '${database_name}'@'localhost';
+GRANT USAGE ON *.* TO '${database_name}'@'127.0.0.1';
+CREATE DATABASE IF NOT EXISTS \`${database_name}\`;
+GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'localhost';
+GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'127.0.0.1';
+FLUSH PRIVILEGES;
+EOF
+
+    else
+        cat >/tmp/.add_mysql.sql<<EOF
 CREATE USER '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
 CREATE USER '${database_name}'@'127.0.0.1' IDENTIFIED BY '${mysql_password}';
 GRANT USAGE ON *.* TO '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
@@ -436,6 +448,8 @@ GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'localhost'
 GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'127.0.0.1';
 FLUSH PRIVILEGES;
 EOF
+
+    fi
     ${MySQL_Bin} --defaults-file=~/.my.cnf < /tmp/.add_mysql.sql
     [ $? -eq 0 ] && echo "Add database Sucessfully." || echo "Add database failed!"
     rm -f /tmp/.add_mysql.sql
@@ -467,9 +481,12 @@ Edit_Database()
             break
         fi
     done
-    db_ver=`${MySQL_Bin} -V | awk '{print $5}' | tr -d ","`
-    if echo ${db_ver} | grep -Eqi '^5.7.';then
+
+    if echo "${MySQL_Ver}" | grep -Eqi '^5.7.';then
         Do_Query "UPDATE mysql.user SET authentication_string=PASSWORD('${database_username_passwd}') WHERE User='${database_username}' AND Host IN ('localhost', '127.0.0.1', '::1');"
+    elif echo "${MySQL_Ver}" | grep -Eqi '^8.0.';then
+        Do_Query "SET PASSWORD FOR '${database_username}'@'127.0.0.1' = '${database_username_passwd}';"
+        Do_Query "SET PASSWORD FOR '${database_username}'@'localhost' = '${database_username_passwd}';"
     else
         Do_Query "UPDATE mysql.user SET Password=PASSWORD('${database_username_passwd}') WHERE User='${database_username}' AND Host IN ('localhost', '127.0.0.1', '::1');"
     fi
@@ -487,7 +504,7 @@ Del_Database()
     fi
     echo "Your will delete database and MySQL user with same name: ${database_name}"
     echo "Sleep 10s, Press ctrl+c to cancel..."
-    sleep 10
+    Sleep_Sec 10
     cat >/tmp/.del.mysql.sql<<EOF
 DROP USER '${database_name}'@'127.0.0.1';
 DROP USER '${database_name}'@'localhost';
@@ -599,7 +616,7 @@ Del_Ftp()
     Enter_Ftp_Name
     echo "Your will delete ftp user ${ftp_account_name}"
     echo "Sleep 10s,Press ctrl+c to cancel..."
-    sleep 10
+    Sleep_Sec 10
     /usr/local/pureftpd/bin/pure-pw userdel ${ftp_account_name} -f /usr/local/pureftpd/etc/pureftpd.passwd -m
     [ $? -eq 0 ] && echo "FTP User: ${ftp_account_name} deleted Sucessfully." || echo "FTP User: ${ftp_account_name} not exists!"
 }
@@ -649,6 +666,7 @@ Add_SSL_Info_Menu()
     if [[ "${access_log}" == "n" || "${access_log}" == "" ]]; then
         echo "Disable access log."
         al="access_log off;"
+        al_name="${domain}"
     else
         Echo_Yellow "Enter access log filename(Default:${domain}.log): "
         read al_name
@@ -660,16 +678,14 @@ Add_SSL_Info_Menu()
     fi
 
     email=""
-    while :;do
-        Echo_Yellow "Please enter Administrator Email Address: "
-        read email
-        if [ "${email}" == "" ]; then
-            Echo_Red "Administrator Email Address cannot be empty!"
-        else
-            echo "Server Administrator Email:${email}"
-            break
-        fi
-    done
+    Echo_Yellow "Please enter Administrator Email Address: "
+    read email
+    if [ "${email}" == "" ]; then
+        echo "Administrator Email Address will set to webmaster@example.com!"
+        email='webmaster@example.com'
+    else
+        echo "Server Administrator Email:${email}"
+    fi
 }
 
 Add_SSL_Menu()
@@ -701,6 +717,15 @@ Add_SSL_Menu()
                     break
                 fi
             done
+            while :;do
+                Echo_Yellow "Please enter full path to SSL Chain file: "
+                read ssl_certificate_key
+                if [ "${ssl_chain}" == "" ]; then
+                    Echo_Yellow "SSL Chain file will not set."
+                    Conf_SSLChain="#SSLCertificateChainFile /path/to/your/chain.pem"
+                    break
+                fi
+            done
             break
         elif [ "${ssl_choice}" == "2" ]; then
             echo "It will be processed automatically."
@@ -713,49 +738,41 @@ Add_SSL_Menu()
 
 Add_Letsencrypt()
 {
-    if [[ "${email}" == "" || "${vhostdir}" == "" || "${letsdomain}" == "" ]]; then
-        Echo_Red "Three parameters are needed!"
+    if [[ "${vhostdir}" == "" || "${letsdomain}" == "" ]]; then
+        Echo_Red "Two parameters are needed!"
         exit 1
     fi
     if [ ! -d "${vhostdir}" ]; then
         Echo_Red "${vhostdir} does not exist or is not a directory!"
         exit
     fi
-    if [ -s /bin/certbot ]; then
-        echo "/bin/certbot [found]"
+    if [ -s /usr/local/acme.sh/acme.sh ]; then
+        echo "/usr/local/acme.sh/acme.sh [found]"
     else
-        wget https://dl.eff.org/certbot-auto --no-check-certificate -O /bin/certbot
-        chmod +x /bin/certbot
-        if grep -Eqi "CentOS" /etc/issue || grep -Eq "CentOS" /etc/*-release; then
-            yum -y install epel-release
-        fi
+        cd /tmp
+        [[ -s latest.tar.gz ]] && rm -f latest.tar.gz
+        wget https://soft.vpser.net/lib/acme.sh/latest.tar.gz --prefer-family=IPv4 --no-check-certificate
+        tar zxf latest.tar.gz
+        cd acme.sh-*
+        ./acme.sh --install --log --home /usr/local/acme.sh --certhome /usr/local/apache/conf/ssl
+        cd ..
+        rm -f latest.tar.gz
+        rm -rf acme.sh-*
+        sed -i 's/cat "\$CERT_PATH"$/#cat "\$CERT_PATH"/g' /usr/local/acme.sh/acme.sh
     fi
 
-    country=`curl -sSk --connect-timeout 10 -m 60 https://ip.vpser.net/country`
-    if [ "${country}" = "CN" ]; then
-        if [ -s ~/.pip/pip.conf ]; then
-            grep "index-url" ~/.pip/pip.conf
-            echo "pip.conf exist."
-        else
-            echo "Create pip.conf..."
-            mkdir ~/.pip
-            cat > ~/.pip/pip.conf <<EOF
-[global]
-index-url = https://pypi.doubanio.com/simple/
+    . "/usr/local/acme.sh/acme.sh.env"
 
-[install]
-trusted-host=pypi.doubanio.com
-EOF
-        fi
-        sed -i 's#pypi.python.org/packages#pypi.doubanio.com/packages#g' /bin/certbot
+    if [ -s /usr/local/apache/conf/ssl/${domain}/fullchain.cer ]; then
+        echo "Removing exist domain certificate..."
+        rm -rf /usr/local/apache/conf/ssl/${domain}
     fi
 
     echo "Starting create SSL Certificate use Let's Encrypt..."
-    /bin/certbot certonly --email ${email} --agree-tos -n --webroot -w ${vhostdir} ${letsdomain}
+    /usr/local/acme.sh/acme.sh --issue ${letsdomain} -w ${vhostdir} --reloadcmd "/etc/init.d/httpd graceful"
     lets_status=$?
     if [ "${lets_status}" = 0 ]; then
-        Check_Lets_Cron
-        echo "Let's Encrypt SSL Certificate create successfully."
+        Echo_Green "Let's Encrypt SSL Certificate create successfully."
     else
         Echo_Red "Let's Encrypt SSL Certificate create failed!"
     fi
@@ -763,6 +780,15 @@ EOF
 
 Create_SSL_Config()
 {
+    if /usr/local/apache/bin/httpd -v|grep -Eqi "Apache/2.4.*"; then
+        Conf_H2='Protocols h2 h2c http/1.1'
+    else
+        Conf_H2=''
+    fi
+    if [ "${ssl_choice}" == "2" ]; then
+        Conf_SSLChain="SSLCertificateChainFile /usr/local/apache/conf/ssl/${domain}/ca.cer"
+    fi
+
     sed -i 's@#Include conf/extra/httpd-ssl.conf@Include conf/extra/httpd-ssl.conf@g' /usr/local/apache/conf/httpd.conf
     cat >>"/usr/local/apache/conf/vhost/${domain}.conf"<<EOF
 
@@ -776,6 +802,8 @@ CustomLog "/home/wwwlogs/${al_name}-access_log" combined
 SSLEngine on
 SSLCertificateFile ${ssl_certificate}
 SSLCertificateKeyFile ${ssl_certificate_key}
+${Conf_SSLChain}
+${Conf_H2}
 <Directory "${vhostdir}">
     SetOutputFilter DEFLATE
     Options FollowSymLinks
@@ -824,21 +852,89 @@ Add_SSL()
             mkdir -p "${vhostdir}"
         fi
         Add_Letsencrypt
-        ssl_certificate="/etc/letsencrypt/live/${domain}/fullchain.pem"
-        ssl_certificate_key="/etc/letsencrypt/live/${domain}/privkey.pem"
+        ssl_certificate="/usr/local/apache/conf/ssl/${domain}/${domain}.cer"
+        ssl_certificate_key="/usr/local/apache/conf/ssl/${domain}/${domain}.key"
         if [ "${lets_status}" = 0 ]; then
             Create_SSL_Config
         fi
     fi
 }
 
-Check_Lets_Cron()
+Add_Dns_SSL()
 {
-    if crontab -l|grep -q "/bin/certbot renew --disable-hook-validation";then
-        echo "Let's encrypt crontab renew rule is exist."
+    provider=$1
+    if [ "${provider}" != "" ]; then
+        dns_provider="dns_${provider}"
     else
-        echo "Add Let's encrypt crontab renew rule..."
-        (crontab -l ; echo '0 3 */7 * * /bin/certbot renew --disable-hook-validation --renew-hook "/etc/init.d/httpd restart"') | crontab -
+        Echo_Red "The dns manual mode can not renew automatically, you must renew it manually."
+    fi
+    if [ -s /usr/local/acme.sh/acme.sh ]; then
+        echo "/usr/local/acme.sh/acme.sh [found]"
+    else
+        cd /tmp
+        [[ -f latest.tar.gz ]] && rm -f latest.tar.gz
+        wget https://soft.vpser.net/lib/acme.sh/latest.tar.gz --prefer-family=IPv4 --no-check-certificate
+        tar zxf latest.tar.gz
+        cd acme.sh-*
+        ./acme.sh --install --log --home /usr/local/acme.sh --certhome /usr/local/apache/conf/ssl
+        cd ..
+        rm -f latest.tar.gz
+        rm -rf acme.sh-*
+        sed -i 's/cat "\$CERT_PATH"$/#cat "\$CERT_PATH"/g' /usr/local/acme.sh/acme.sh
+    fi
+    if [[ ! -s /usr/local/acme.sh/dnsapi/dns_${provider}.sh && "${provider}" != "" ]]; then
+        echo "DNS Provider: ${provider} not found."
+        exit 1
+    fi
+    Add_SSL_Info_Menu
+
+    . "/usr/local/acme.sh/acme.sh.env"
+
+    if [ -s /usr/local/apache/conf/ssl/${domain}/fullchain.cer ]; then
+        echo "Removing exist domain certificate..."
+        rm -rf /usr/local/apache/conf/ssl/${domain}
+    fi
+
+    letsdomain=""
+    if [ "${moredomain}" != "" ]; then
+        letsdomain="-d ${domain}"
+        for i in ${moredomain};do
+            letsdomain=${letsdomain}" -d ${i}"
+        done
+    else
+        letsdomain="-d ${domain}"
+    fi
+
+    echo "Starting create SSL Certificate use Let's Encrypt..."
+    if [ "${provider}" != "" ]; then
+        /usr/local/acme.sh/acme.sh --issue ${letsdomain} --dns ${dns_provider} --reloadcmd "/etc/init.d/httpd graceful"
+        lets_status=$?
+    else
+        /usr/local/acme.sh/acme.sh --issue ${letsdomain} --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please
+        Echo_Yellow "Please add the above TXT record to the domain in 120 seconds!!!"
+        echo
+        Sleep_Sec 120
+        /usr/local/acme.sh/acme.sh --renew ${letsdomain}
+        lets_status=$?
+    fi
+    if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/apache/conf/ssl/${domain}/${domain}.cer" ]]; then
+        if [ ! -d "${vhostdir}" ]; then
+            echo "Create Virtul Host directory......"
+            mkdir -p ${vhostdir}
+            echo "set permissions of Virtual Host directory......"
+            chmod -R 755 ${vhostdir}
+            chown -R www:www ${vhostdir}
+        fi
+
+        if [ ! -s "/usr/local/apache/conf/vhost/${domain}.conf" ]; then
+            Add_VHost_Config
+        fi
+        ssl_certificate="/usr/local/apache/conf/ssl/${domain}/${domain}.cer"
+        ssl_certificate_key="/usr/local/apache/conf/ssl/${domain}/${domain}.key"
+        Create_SSL_Config
+        Echo_Green "Let's Encrypt SSL Certificate create successfully."
+    else
+        Echo_Red "Let's Encrypt SSL Certificate create failed!"
     fi
 }
 
@@ -865,6 +961,18 @@ Echo_Yellow()
 Echo_Blue()
 {
   echo $(Color_Text "$1" "34")
+}
+
+Sleep_Sec()
+{
+    seconds=$1
+    while [ "${seconds}" -ge "0" ];do
+      echo -ne "\r     \r"
+      echo -n ${seconds}
+      seconds=$(($seconds - 1))
+      sleep 1
+    done
+    echo -ne "\r"
 }
 
 Check_DB
@@ -918,13 +1026,17 @@ case "${arg1}" in
         Add_SSL_Menu
         Add_SSL
         ;;
+    dnsssl|dns)
+        Add_Dns_SSL ${arg2}
+        ;;
     *)
         echo "Usage: lnmp {start|stop|reload|restart|kill|status}"
-        echo "Usage: lnmp {nginx|mysql|mariadb|pureftpd|httpd} {start|stop|reload|restart|kill|status}"
+        echo "Usage: lnmp {httpd|mysql|mariadb|pureftpd} {start|stop|reload|restart|kill|status}"
         echo "Usage: lnmp vhost {add|list|del}"
         echo "Usage: lnmp database {add|list|edit|del}"
         echo "Usage: lnmp ftp {add|list|edit|del|show}"
         echo "Usage: lnmp ssl add"
+        echo "Usage: lnmp {dnsssl|dns} {cx|ali|cf|dp|he|gd|aws}"
         ;;
 esac
 exit
